branches:
  exclude: [gh-pages]

clone:
  git:
    image: plugins/git
    commands:
      - if  [ "${DRONE_BUILD_EVENT}" == "deployment" ] ; then
          echo "Skipping git init/clone :)";
        else
          git init;
          git remote add origin "${DRONE_REMOTE_URL}";
          git fetch --no-tags --depth 1 origin "${DRONE_COMMIT_REF}";
          if [ "${DRONE_BUILD_EVENT}" == "pull_request" ] || [ "${DRONE_BUILD_EVENT}" == "tag" ] ; then
            git checkout -qf FETCH_HEAD;
          else
            git reset --hard -q "${DRONE_COMMIT_SHA}";
          fi
        fi

matrix:
  TEST:
    - audit
    - conventions
    - examples
    - size
    - deploy

pipeline:
  install:
    image: node:erbium
    commands:
      - export NOYARNPOSTINSTALL="1"
      - yarn install --frozen-lockfile
    when:
      event: [push, pull_request, tag]

  audit:
    image: node:erbium
    commands:
      - ./scripts/audit.sh
    when:
      event: [push, pull_request, tag]
      matrix:
        TEST: audit

  conventions:
    image: node:erbium
    commands:
      - yarn build:icons
      - yarn build:themes
      - yarn build:presets
      - yarn test:coding-conventions
    when:
      event: [push, pull_request, tag]
      matrix:
        TEST: conventions

  examples:
    image: node:erbium
    commands:
      - yarn build:icons
      - yarn build:themes
      - yarn build:presets
      - cd examples/webpack4 && yarn build --display=errors-only
      - cd ../webpack4-eu && yarn build --display=errors-only
    when:
      event: [push, pull_request, tag]
      matrix:
        TEST: examples

  size:
    image: buildkite/puppeteer:5.2.1
    commands:
      - yarn clean
      - yarn build:themes
      - yarn dist:presets
      - yarn size-limit
    when:
      event: [push, pull_request, tag]
      matrix:
        TEST: size

  # =======================================
  # Deployment (tag) ======================
  # =======================================

  build-presets:
    image: node:erbium
    commands:
      - yarn browserstats
      - yarn clean
      - yarn build:icons
      - yarn build:themes
      - yarn dist:presets
    when:
      ref:
        include:
          - refs/tags/v2*
      matrix:
        TEST: deploy

  build-website:
    image: buildkite/puppeteer:5.2.1
    commands:
      - export PUBLIC_URL="/component-library"
      - node scripts/sri.js
      - npm run dist:storybook
      - npm run dist:website
      - echo ${DRONE_TAG=${DRONE_COMMIT_BRANCH=rc}} > dist/website/.version
      - echo ${DRONE_COMMIT_SHA} > dist/website/.commit
    when:
      ref:
        include:
          - refs/tags/v2*
      matrix:
        TEST: deploy

  # Package release build
  package-release:
    image: samdze/alpine-zip
    commands:
      - cd dist/website
      - zip ${DRONE_REPO_NAME}-${DRONE_TAG}.zip .
      - cp dist/packages/${DRONE_REPO_NAME}-${DRONE_TAG}-sri.json .
    when:
      ref:
        include:
          - refs/tags/v2*
      matrix:
        TEST: deploy

  # Push release to Github
  push-github-release:
    image: plugins/github-release
    files:
      - ${DRONE_REPO_NAME}-${DRONE_TAG}.zip
      - ${DRONE_REPO_NAME}-${DRONE_TAG}-sri.json
    checksum:
      - sha1
    secrets: [GITHUB_RELEASE_API_KEY]
    when:
      ref:
        include:
          - refs/tags/v2*
      matrix:
        TEST: deploy

  # Make a second copy of the website for versions archives.
  build-archive:
    image: buildkite/puppeteer:5.2.1
    commands:
      - rm -rf dist/website
      - export PUBLIC_URL="/component-library/${DRONE_TAG}"
      - npm run dist:website
      - echo ${DRONE_TAG=${DRONE_COMMIT_BRANCH=rc}} > dist/website/.version
      - echo ${DRONE_COMMIT_SHA} > dist/website/.commit
    when:
      ref:
        include:
          - refs/tags/v2*
      matrix:
        TEST: deploy

  package-archive:
    image: samdze/alpine-zip
    commands:
      - cd dist/website
      - zip ${DRONE_REPO_NAME}-${DRONE_TAG}-archive.zip .
    when:
      ref:
        include:
          - refs/tags/v2*
      matrix:
        TEST: deploy

  upload-archive:
    image: plugins/github-release
    files:
      - ${DRONE_REPO_NAME}-${DRONE_TAG}-archive.zip
    checksum:
      - sha1
    secrets: [GITHUB_RELEASE_API_KEY]
    when:
      ref:
        include:
          - refs/tags/v2*
      matrix:
        TEST: deploy

  # =======================================
  # Deployment (dev) ======================
  # =======================================

  deploy-netlify-preview:
    image: buildkite/puppeteer:5.2.1
    secrets: [gh_token, netlify_auth_token, netlify_site_id]
    commands:
      - yarn clean
      - yarn build:icons
      - yarn build:themes
      - yarn dist
      - 'yarn netlify deploy --site $${NETLIFY_SITE_ID} --alias ${DRONE_COMMIT_BRANCH} --message "Drone build: ${DRONE_BUILD_NUMBER}"'
      - node scripts/set-netlify-deployment-status.js
    when:
      event: [push, pull_request]
      status: [success, failure]
      matrix:
        TEST: deploy
